import pytest
from typing import Any
from playwright.sync_api import Page
from pytest_metadata.plugin import metadata_key


# ============================================================
# PAGE FIXTURES
# ============================================================

@pytest.fixture
def practice_page1(page: Page):
    page.goto(
        "https://automatewithbipin.com/?utm_source=chatgpt.com"
    )
    return page


@pytest.fixture
def orangehrm(page: Page):
    page.goto(
        "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
    )
    return page


@pytest.fixture
def assertqa(page: Page):
    page.goto(
        "https://assertqa.com/practice/webtables?utm_source=chatgpt.com"
    )
    return page


@pytest.fixture
def practiceplaywright(page: Page):
    page.goto(
        "https://testautomationpractice.blogspot.com/"
        "p/playwrightpractice.html"
    )
    return page


@pytest.fixture
def qaplayground(page: Page):
    page.goto(
        "https://qaplayground.com/practice/date-picker?utm_source=chatgpt.com"
    )
    return page


@pytest.fixture
def demowebshop(page: Page):
    page.goto(
        "https://demowebshop.tricentis.com/"
    )
    return page


@pytest.fixture
def demowebshoploginpage(page: Page):
    page.goto(
        "https://demowebshop.tricentis.com/login"
    )
    return page


# ============================================================
# PYTEST HTML REPORT - METADATA
# ============================================================

def pytest_configure(config: pytest.Config) -> None:
    config.stash[metadata_key]["Project"] = "Demo WebShop Automation"
    config.stash[metadata_key]["Tester"] = "Ragul"
    config.stash[metadata_key]["Browser"] = "Chromium"
    config.stash[metadata_key]["Mode"] = "Headed"


def pytest_metadata(metadata: dict[str, Any]) -> None:
    metadata.pop("JAVA_HOME", None)
    metadata.pop("Plugins", None)


# ============================================================
# REPORT TITLE
# ============================================================

def pytest_html_report_title(report: Any) -> None:
    report.title = "Automation Test Report"


# ============================================================
# REPORT SUMMARY
# ============================================================

def pytest_html_results_summary(
    prefix: list[str],
    summary: list[str],
    postfix: list[str],
) -> None:
    prefix.extend(
        [
            "<p><strong>Generated by Pytest + Playwright</strong></p>"
        ]
    )


# ============================================================
# DESCRIPTION COLUMN
# ============================================================

def pytest_html_results_table_header(cells: Any) -> None:
    cells.insert(
        2,
        "<th>Description</th>"
    )


def pytest_html_results_table_row(
    report: Any,
    cells: Any,
) -> None:
    description = getattr(
        report,
        "description",
        "N/A"
    )

    cells.insert(
        2,
        f"<td>{description}</td>"
    )


# ============================================================
# TEST DESCRIPTION
# ============================================================

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(
    item: pytest.Item,
    call: pytest.CallInfo[Any],
) -> Any:

    outcome = yield

    report = outcome.get_result()

    if report.when == "call":
        report.description = (
            item.function.__doc__
            or "No description provided"
        )